name: Variable-env-secret
on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      ECOLE: ForEach
    steps:
      - name: "Dit bonjour"
        run: echo "Salut ${{ secrets.NAME }} ! Je suis formateur pour $ECOLE. On est  $DAY"
        env:
          DAY: Mercredi
      - name: "Mercredi ?"
        run: echo "Somme nous $DAY ?"
  say_goodbay:
    runs-on: ubuntu-latest
    steps:
      - name: "Aurevoir"
        run: echo "Au revoir ${{ secrets.NAME }} de $ECOLE, bon $DAY"
